//get all the pokemon availible
export const FETCH_ALL_POKEMON_REQUEST = "FETCH_ALL_POKEMON_REQUEST";
export const FETCH_ALL_POKEMON_SUCCESS = "FETCH_ALL_POKEMON_SUCCESS";
export const FETCH_ALL_POKEMON_FAIL = "FETCH_ALL_POKEMON_FAIL";

//get single pokemon
export const FETCH_SINGLE_POKEMON_REQUEST = "FETCH_SINGLE_POKEMON_REQUEST";
export const FETCH_SINGLE_POKEMON_SUCCESS = "FETCH_SINGLE_POKEMON_SUCCESS";
export const FETCH_SINGLE_POKEMON_FAIL = "FETCH_SINGLE_POKEMON_FAIL";
