//constants for login
export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";

//constants for register
export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";

//constants to get user info
export const USER_DETAILS_REQUEST = "USER_DETAILS_REQUEST";
export const USER_DETAILS_SUCCESS = "USER_DETAILS_SUCCESS";
export const USER_DETAILS_FAIL = "USER_DETAILS_FAIL";
export const USER_DETAILS_RESET = "USER_DETAILS_RESET";

export const USER_LOGOUT = "USER_LOGOUT";

//constatns to add pokemon to deck
export const USER_ADD_POKEMON_REQUEST = "USER_ADD_POKEMON_REQUEST";
export const USER_ADD_POKEMON_SUCCESS = "USER_ADD_POKEMON_SUCCESS";
export const USER_ADD_POKEMON_FAIL = "USER_ADD_POKEMON_FAIL";
